Repository andrewjj20/post, pull requests merged in 2020-10, with the labels that each got.

#22 Establishes common setup/teardown methods for tests
  tests/src/common/find_service_setup.rs
  tests/src/common/mod.rs
  tests/src/lib.rs
  tests/src/publisher_subscriber.rs
  tests/tests/publister_subscriber.rs
Labels: test fix

#32 Set up rust github actions
  .github/workflows/rust.yml
Labels: hacktoberfest-accepted

#36 actions: Add rustfmt to list of checks
  .github/workflows/rust.yml
  examples/stdin_publisher.rs
  tests/src/lib.rs
Labels: hacktoberfest-accepted

#34 No async closures
  .github/workflows/rust.yml
  examples/stdout_subscriber.rs
  lib/src/lib.rs
  lib/src/publisher.rs
  lib/src/subscriber.rs
Labels: hacktoberfest-accepted

#31 Splits MeetupServer into its own module
  meetup/Cargo.toml
  meetup/src/lib.rs
  meetup/src/main.rs
Labels: enhancement, good first issue, hacktoberfest-accepted
